apiVersion: v1
kind: Service
metadata:
  name: keycloak-app
spec:
  selector:
    app: keycloak-app
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-app
  labels:
    app: keycloak-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
        - name: keycloak-app
          image: quay.io/keycloak/keycloak:18.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - protocol: TCP
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8443
              scheme: HTTPS
          env:
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8"
            - name: KC_PROXY
              value: edge
          envFrom:
            - configMapRef:
                name: keycloak-config
          workingDir: /opt/keycloak
          command: ["/bin/sh", "-c"]
          args:
            - |
              bin/kc.sh start --auto-build --hostname=keycloak.192.168.64.8.nip.io \
                --https-certificate-file=/auth/keycloak-crt.pem \
                --https-certificate-key-file=/auth/keycloak-key.pem
          volumeMounts:
            - mountPath: /auth
              name: keycloak-app
              subPath: auth
      volumes:
      - name: keycloak-app
        persistentVolumeClaim:
          claimName: keycloak-app
