apiVersion: v1
kind: Service
metadata:
  name: keycloak-app
spec:
  selector:
    app: keycloak-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-app
  labels:
    app: keycloak-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
        - name: keycloak-app
          image: quay.io/keycloak/keycloak:18.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - protocol: TCP
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
          env:
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8"
            - name: KC_HTTP_ENABLED
              value: "true"
            
          envFrom:
            - configMapRef:
                name: keycloak-config
          args:
            - start-dev
