apiVersion: v1
kind: Service
metadata:
  name: keycloak-app
spec:
  selector:
    app: keycloak-app
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-app
  labels:
    app: keycloak-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
        - name: keycloak-app
          image: quay.io/keycloak/keycloak:18.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - protocol: TCP
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8443
              scheme: HTTPS
          envFrom:
            - configMapRef:
                name: keycloak-config
          args:
            - |
              start-dev
